server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/face?useUnicode=true&characterEncoding=utf8
    username: face
    password: face

